In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
np.version.version


'1.14.0'

In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

'''
L.S. Good!
'''

a = np.random.random((2,5,3))



In [4]:
#4. Print a.
print(a)

[[[9.31878571e-02 8.08646530e-01 3.39790697e-01]
  [6.74575516e-04 7.61707679e-01 6.77967399e-01]
  [7.07715941e-01 7.42239749e-01 1.51614522e-01]
  [2.63759006e-01 4.74251610e-01 9.19871635e-01]
  [4.95589316e-01 7.21760830e-01 1.38319443e-01]]

 [[3.40537420e-01 9.77229488e-01 8.42966303e-01]
  [6.51913985e-01 7.23732758e-01 6.20248584e-01]
  [8.94460150e-01 9.51145107e-01 1.78151019e-01]
  [1.19153686e-01 2.82325281e-01 6.17083224e-01]
  [9.80701180e-01 8.19907223e-01 5.46284762e-01]]]


In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

'''
L.S. Correct!
'''

b = np.ones((5,2,3))

#6. Print b.
print (b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [18]:
#7. Do a and b have the same size? How do you prove that in Python code?

'''
L.S. Yes, correct. 
'''

len(b) == len (a)
#this indicates false and shows tahs both matrixxes do not have the same len or structure at least 
d = a+b # if this is not possible is enforces the assumption above 
#print(np.len(a)), this atribute doe snot excist 


False

In [7]:
#8. Are you able to add a and b? Why or why not?
d = a+b
print (c)

'''
L.S. Correct. 
'''

# it is possible as long the matrixes have the same size, this is not the case

ValueError: operands could not be broadcast together with shapes (2,5,3) (5,2,3) 

In [8]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


c = np.transpose(b.reshape(3,5,2))

'''
L.S. Space in statement not necessary. 
'''

print (c)




[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [20]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
'''
L.S. Be careful here, it does not work, because 'g' is not defined. I assume you meant to use 'b'?
'''

d = a+c
print (g)

print("sum d: ", np.sum(d))

# it works because the structure of the matrix is teh same 

[[[1.09318786 1.80864653 1.3397907 ]
  [1.00067458 1.76170768 1.6779674 ]
  [1.70771594 1.74223975 1.15161452]
  [1.26375901 1.47425161 1.91987163]
  [1.49558932 1.72176083 1.13831944]]

 [[1.34053742 1.97722949 1.8429663 ]
  [1.65191398 1.72373276 1.62024858]
  [1.89446015 1.95114511 1.17815102]
  [1.11915369 1.28232528 1.61708322]
  [1.98070118 1.81990722 1.54628476]]]
sum d:  46.84293696050522


In [10]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print (a)
print (d)

#at d all the values of a are a al exacte 1 value higher. 

[[[9.31878571e-02 8.08646530e-01 3.39790697e-01]
  [6.74575516e-04 7.61707679e-01 6.77967399e-01]
  [7.07715941e-01 7.42239749e-01 1.51614522e-01]
  [2.63759006e-01 4.74251610e-01 9.19871635e-01]
  [4.95589316e-01 7.21760830e-01 1.38319443e-01]]

 [[3.40537420e-01 9.77229488e-01 8.42966303e-01]
  [6.51913985e-01 7.23732758e-01 6.20248584e-01]
  [8.94460150e-01 9.51145107e-01 1.78151019e-01]
  [1.19153686e-01 2.82325281e-01 6.17083224e-01]
  [9.80701180e-01 8.19907223e-01 5.46284762e-01]]]
[[[1.09318786 1.80864653 1.3397907 ]
  [1.00067458 1.76170768 1.6779674 ]
  [1.70771594 1.74223975 1.15161452]
  [1.26375901 1.47425161 1.91987163]
  [1.49558932 1.72176083 1.13831944]]

 [[1.34053742 1.97722949 1.8429663 ]
  [1.65191398 1.72373276 1.62024858]
  [1.89446015 1.95114511 1.17815102]
  [1.11915369 1.28232528 1.61708322]
  [1.98070118 1.81990722 1.54628476]]]


In [11]:
#12. Multiply a and c. Assign the result to e.

e = a*c
print (a)
print (c)
print (e)

[[[9.31878571e-02 8.08646530e-01 3.39790697e-01]
  [6.74575516e-04 7.61707679e-01 6.77967399e-01]
  [7.07715941e-01 7.42239749e-01 1.51614522e-01]
  [2.63759006e-01 4.74251610e-01 9.19871635e-01]
  [4.95589316e-01 7.21760830e-01 1.38319443e-01]]

 [[3.40537420e-01 9.77229488e-01 8.42966303e-01]
  [6.51913985e-01 7.23732758e-01 6.20248584e-01]
  [8.94460150e-01 9.51145107e-01 1.78151019e-01]
  [1.19153686e-01 2.82325281e-01 6.17083224e-01]
  [9.80701180e-01 8.19907223e-01 5.46284762e-01]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[9.31878571e-02 8.08646530e-01 3.39790697e-01]
  [6.74575516e-04 7.61707679e-01 6.77967399e-01]
  [7.07715941e-01 7.42239749e-01 1.51614522e-01]
  [2.63759006e-01 4.74251610e-01 9.19871635e-01]
  [4.95589316e-01 7.21760830e-01 1.38319443e-01]]

 [[3.40537420e-01 9.77229488e-01 8.42966303e-01]
  [6.51913985e-01 7.23732758e-01 6.20248584e-01]
  [8.94460150e-01 9.5114510

In [12]:
#13. Does e equal to a? Why or why not?
# yes is equal, because 1 *x = x 


In [13]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

'''
L.S. Looks good!
'''

d_max = (np.mean(d))
d_min = (np.min(d))
d_mean = (np.mean(d))

print("d_max: ", d_max)
print("d_min: ", d_min)
print("d_mean: ", d_mean)

d_max:  1.5614312320168406
d_min:  1.0006745755158981
d_mean:  1.5614312320168406


In [21]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2,3,5))
print(f)
print (d)

[[[1.09318786 1.80864653 1.3397907  1.00067458 1.76170768]
  [1.6779674  1.70771594 1.74223975 1.15161452 1.26375901]
  [1.47425161 1.91987163 1.49558932 1.72176083 1.13831944]]

 [[1.34053742 1.97722949 1.8429663  1.65191398 1.72373276]
  [1.62024858 1.89446015 1.95114511 1.17815102 1.11915369]
  [1.28232528 1.61708322 1.98070118 1.81990722 1.54628476]]]
[[[1.09318786 1.80864653 1.3397907 ]
  [1.00067458 1.76170768 1.6779674 ]
  [1.70771594 1.74223975 1.15161452]
  [1.26375901 1.47425161 1.91987163]
  [1.49558932 1.72176083 1.13831944]]

 [[1.34053742 1.97722949 1.8429663 ]
  [1.65191398 1.72373276 1.62024858]
  [1.89446015 1.95114511 1.17815102]
  [1.11915369 1.28232528 1.61708322]
  [1.98070118 1.81990722 1.54628476]]]


In [15]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
# d_min < d[i] < d_mean --> f[d] = 25 
# d_mean < d[i]  --> f[d] = 75 



"\n#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.\nIf a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.\nIf a value equals to d_mean, assign 50 to the corresponding value in f.\nAssign 0 to the corresponding value(s) in f for d_min in d.\nAssign 100 to the corresponding value(s) in f for d_max in d.\nIn the end, f should have only the following values: 0, 25, 50, 75, and 100.\nNote: you don't have to use Numpy in this question.\n"

In [16]:

"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""


'\n#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values \n("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:\narray([[[ \'D\',  \'D\',  \'D\',  \'B\',  \'D\'],\n        [ \'D\',  \'D\',  \'B\',  \'B\',  \'B\'],\n        [ \'D\',  \'B\',  \'D\',  \'D\',  \'D\']],\n\n       [[ \'B\',  \'B\',  \'B\',  \'B\',  \'E\'],\n        [ \'D\',  \'D\',  \'D\',  \'D\',  \'D\'],\n        [ \'B\',  \'D\',   \'A\',  \'D\', \'D\']]])\nAgain, you don\'t need Numpy in this question.\n'