In [1]:
#1. Import the NUMPY package under the name np.
import numpy as np

In [2]:
#2. Print the NUMPY version and the configuration.
np.version.version


'1.17.2'

In [3]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

a = np.random.random((2,5,3))



In [4]:
#4. Print a.
print(a)

[[[0.38287856 0.28727782 0.52522879]
  [0.50650808 0.74237652 0.16918115]
  [0.77135336 0.39952391 0.12114608]
  [0.88987938 0.92657367 0.33839098]
  [0.32679643 0.46269388 0.64793907]]

 [[0.14710925 0.83383313 0.48625891]
  [0.19426527 0.98594226 0.04543848]
  [0.07768086 0.98477749 0.64243745]
  [0.72065324 0.68603433 0.87759951]
  [0.94227265 0.65537655 0.77974141]]]


In [5]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5,2,3))

#6. Print b.
print (b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [6]:
#7. Do a and b have the same size? How do you prove that in Python code?

len(b) == len (a)
#this indicates false and shows tahs both matrixxes do not have the same len or structure at least 
d = a+b # if this is not possible is enforces the assumption above 
#print(np.len(a)), this atribute doe snot excist 


ValueError: operands could not be broadcast together with shapes (2,5,3) (5,2,3) 

In [7]:
#8. Are you able to add a and b? Why or why not?
d = a+b
print (c)

# it is possible as long the matrixes have the same size, this is not the case

ValueError: operands could not be broadcast together with shapes (2,5,3) (5,2,3) 

In [19]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


c = np.transpose(b.reshape(3,5,2))

print (c)




[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [9]:
#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = a+c
print (g)

print("sum d: ", np.sum(d))

# it works because the structure of the matrix is teh same 

NameError: name 'g' is not defined

In [10]:
#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

print (a)
print (d)

#at d all the values of a are a al exacte 1 value higher. 

[[[0.38287856 0.28727782 0.52522879]
  [0.50650808 0.74237652 0.16918115]
  [0.77135336 0.39952391 0.12114608]
  [0.88987938 0.92657367 0.33839098]
  [0.32679643 0.46269388 0.64793907]]

 [[0.14710925 0.83383313 0.48625891]
  [0.19426527 0.98594226 0.04543848]
  [0.07768086 0.98477749 0.64243745]
  [0.72065324 0.68603433 0.87759951]
  [0.94227265 0.65537655 0.77974141]]]
[[[1.38287856 1.28727782 1.52522879]
  [1.50650808 1.74237652 1.16918115]
  [1.77135336 1.39952391 1.12114608]
  [1.88987938 1.92657367 1.33839098]
  [1.32679643 1.46269388 1.64793907]]

 [[1.14710925 1.83383313 1.48625891]
  [1.19426527 1.98594226 1.04543848]
  [1.07768086 1.98477749 1.64243745]
  [1.72065324 1.68603433 1.87759951]
  [1.94227265 1.65537655 1.77974141]]]


In [12]:
#12. Multiply a and c. Assign the result to e.

e = a*c
print (a)
print (c)
print (e)

[[[0.38287856 0.28727782 0.52522879]
  [0.50650808 0.74237652 0.16918115]
  [0.77135336 0.39952391 0.12114608]
  [0.88987938 0.92657367 0.33839098]
  [0.32679643 0.46269388 0.64793907]]

 [[0.14710925 0.83383313 0.48625891]
  [0.19426527 0.98594226 0.04543848]
  [0.07768086 0.98477749 0.64243745]
  [0.72065324 0.68603433 0.87759951]
  [0.94227265 0.65537655 0.77974141]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[0.38287856 0.28727782 0.52522879]
  [0.50650808 0.74237652 0.16918115]
  [0.77135336 0.39952391 0.12114608]
  [0.88987938 0.92657367 0.33839098]
  [0.32679643 0.46269388 0.64793907]]

 [[0.14710925 0.83383313 0.48625891]
  [0.19426527 0.98594226 0.04543848]
  [0.07768086 0.98477749 0.64243745]
  [0.72065324 0.68603433 0.87759951]
  [0.94227265 0.65537655 0.77974141]]]


In [ ]:
#13. Does e equal to a? Why or why not?
# yes is equal, because 1 *x = x 


In [13]:
#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

d_max = (np.mean(d))
d_min = (np.min(d))
d_mean = (np.mean(d))

print("d_max: ", d_max)
print("d_min: ", d_min)
print("d_mean: ", d_mean)

d_max:  1.5519056157913185
d_min:  1.045438484718677
d_mean:  1.5519056157913185


In [21]:
#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty((2,3,5))
print(f)
print (d)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[[[1.38287856 1.28727782 1.52522879]
  [1.50650808 1.74237652 1.16918115]
  [1.77135336 1.39952391 1.12114608]
  [1.88987938 1.92657367 1.33839098]
  [1.32679643 1.46269388 1.64793907]]

 [[1.14710925 1.83383313 1.48625891]
  [1.19426527 1.98594226 1.04543848]
  [1.07768086 1.98477749 1.64243745]
  [1.72065324 1.68603433 1.87759951]
  [1.94227265 1.65537655 1.77974141]]]


In [ ]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""
# d_min < d[i] < d_mean --> f[d] = 25 
# d_mean < d[i]  --> f[d] = 75 



In [8]:

"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""


"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""


'\n#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values \n("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:\narray([[[ \'D\',  \'D\',  \'D\',  \'B\',  \'D\'],\n        [ \'D\',  \'D\',  \'B\',  \'B\',  \'B\'],\n        [ \'D\',  \'B\',  \'D\',  \'D\',  \'D\']],\n\n       [[ \'B\',  \'B\',  \'B\',  \'B\',  \'E\'],\n        [ \'D\',  \'D\',  \'D\',  \'D\',  \'D\'],\n        [ \'B\',  \'D\',   \'A\',  \'D\', \'D\']]])\nAgain, you don\'t need Numpy in this question.\n'